{{- with index .Values "secrets" "chatbot" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  valuefirst-username: {{ .valuefirst_username | b64enc | quote }}
  valuefirst-password: {{ .valuefirst_password | b64enc | quote }}
{{- end }}
