{{- with index .Values "secrets" "egov-user-chatbot" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  citizen-login-password-otp-fixed-value : {{ .citizen_login_password_otp_fixed_value | b64enc | quote }}
{{- end }}