{{- with index .Values "secrets" "egov-si-microservice" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
 si-microservice-password: {{ .si_microservice_password | b64enc | quote }}
 si-microservice-user: {{ .si_microservice_user | b64enc | quote }}
 mail-sender-password: {{ .mail_sender_password | b64enc | quote }}
{{- end }}
