{{- with index .Values "secrets" "egov-edcr-notification" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  mailsenderusername: {{ .edcr_mail_username | b64enc | quote }}
  mailsenderpassword: {{ .edcr_mail_password | b64enc | quote }}
  smssenderusername: {{ .edcr_sms_username | b64enc | quote }}
  smssenderpassword: {{ .edcr_sms_password | b64enc | quote }}
{{- end }}